# This is a sample build configuration for Javascript.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.11.1
pipelines:
  branches:
    development:
      - step:
          script:
            - npm install
            - node test.js